"""Interactive FastHTML dashboard for employee recruitment-risk monitoring."""

import matplotlib.pyplot as plt
from fasthtml.common import (
    Div,
    H1,
    H2,
    P,
    RedirectResponse,
    Style,
    fast_app,
    serve,
)

from employee_events import Employee, QueryBase, Team  # noqa: F401
from utils import load_model, project_root

from base_components import (
    BaseComponent,
    DataTable,
    Dropdown,
    MatplotlibViz,
    Radio,
)
from combined_components import CombinedComponent, FormGroup


class ReportDropdown(Dropdown):
    """Dropdown populated from the selected employee-events query model."""

    def build_component(self, entity_id, model):
        """Build a labeled dropdown for an employee or team."""
        self.label = model.name.title()
        return super().build_component(entity_id, model)

    def component_data(self, entity_id, model):
        """Return names and identifiers for the active profile type."""
        return model.names()


class Header(BaseComponent):
    """Heading that reflects the selected profile type and name."""

    def build_component(self, entity_id, model):
        """Build the dashboard heading and selected-profile subtitle."""
        name_result = model.username(entity_id)
        profile_name = name_result[0][0] if name_result else "Unknown profile"
        return Div(
            H1(f"{model.name.title()} Performance"),
            P(profile_name, cls="profile-name"),
        )


class LineChart(MatplotlibViz):
    """Cumulative positive and negative performance event chart."""

    def visualization(self, entity_id, model):
        """Plot cumulative performance events through time."""
        event_counts = model.event_counts(entity_id).fillna(0)
        event_counts = event_counts.set_index("event_date").sort_index()
        cumulative_counts = event_counts.cumsum()
        cumulative_counts.columns = ["Positive", "Negative"]

        _, ax = plt.subplots(figsize=(9, 4.5))
        cumulative_counts.plot(
            ax=ax,
            color=["#2A9D8F", "#E76F51"],
        )
        self.set_axis_styling(ax, bordercolor="black", fontcolor="black")
        ax.set_title("Cumulative Performance Events", fontsize=20)
        ax.set_xlabel("Event Date")
        ax.set_ylabel("Cumulative Event Count")
        ax.grid(axis="y", alpha=0.25)
        plt.tight_layout()


class BarChart(MatplotlibViz):
    """Recruitment-risk chart generated by the supplied model."""

    predictor = load_model()

    def visualization(self, entity_id, model):
        """Plot an employee risk or a team's average recruitment risk."""
        model_data = model.model_data(entity_id)
        probabilities = self.predictor.predict_proba(model_data)[:, 1]
        prediction = (
            float(probabilities.mean())
            if model.name == "team"
            else float(probabilities[0])
        )

        if prediction < 0.35:
            color = "#2A9D8F"
        elif prediction < 0.65:
            color = "#E9C46A"
        else:
            color = "#E76F51"

        _, ax = plt.subplots(figsize=(9, 2.8))
        ax.barh(["Recruitment risk"], [prediction], color=color)
        ax.set_xlim(0, 1)
        ax.set_title("Predicted Recruitment Risk", fontsize=20)
        ax.set_xlabel("Probability")
        ax.text(
            min(prediction + 0.02, 0.92),
            0,
            f"{prediction:.1%}",
            va="center",
            fontweight="bold",
        )
        self.set_axis_styling(ax, bordercolor="black", fontcolor="black")
        plt.tight_layout()


class Visualizations(CombinedComponent):
    """Dashboard area containing productivity and recruitment visuals."""

    children = [LineChart(), BarChart()]
    outer_div_type = Div(cls="grid")


class NotesTable(DataTable):
    """Table containing the selected profile's performance notes."""

    def component_data(self, entity_id, model):
        """Return notes for the selected employee or team."""
        return model.notes(entity_id)


class DashboardFilters(FormGroup):
    """Employee/team type and profile selection controls."""

    id = "top-filters"
    action = "/update_data"
    method = "POST"
    button_label = "View dashboard"
    children = [
        Radio(
            values=["Employee", "Team"],
            name="profile_type",
            hx_get="/update_dropdown",
            hx_target="#selector",
        ),
        ReportDropdown(id="selector", name="user-selection"),
    ]


class Report(CombinedComponent):
    """Complete employee or team dashboard page."""

    children = [
        Header(),
        DashboardFilters(),
        Visualizations(),
        H2("Performance Notes"),
        NotesTable(),
    ]


stylesheet = (project_root / "assets" / "report.css").read_text()
app, route = fast_app(hdrs=(Style(stylesheet),))
report = Report()


@route("/")
def home():
    """Render the default employee dashboard."""
    return report(1, Employee())


@route("/employee/{entity_id}")
def employee_report(entity_id: str):
    """Render a dashboard for one employee."""
    return report(entity_id, Employee())


@route("/team/{entity_id}")
def team_report(entity_id: str):
    """Render a dashboard for one team."""
    return report(entity_id, Team())


@app.get("/update_dropdown")
def update_dropdown(request):
    """Refresh available names when the profile type changes."""
    dropdown = DashboardFilters.children[1]
    profile_type = request.query_params["profile_type"]
    if profile_type == "Team":
        return dropdown(None, Team())
    return dropdown(None, Employee())


@app.post("/update_data")
async def update_data(request):
    """Redirect a submitted filter form to the selected dashboard."""
    data = await request.form()
    profile_type = data._dict["profile_type"]
    entity_id = data._dict["user-selection"]
    return RedirectResponse(
        f"/{profile_type.lower()}/{entity_id}",
        status_code=303,
    )


if __name__ == "__main__":
    serve()
